### ISSUE TITLE
Ignore IPv6 addresses obtained by autoconf

### ISSUE THREAD

**Issue by naggety** [LNST-project/lnst#210]
Bond and Team recipes had ended with "unexpected error", printing this backtrace:
```
Traceback (most recent call last):
  File "/home/ihuguet/Dev/lnst/./thunderx-nicvf-tests.py", line 49, in <module>
    ctl.run(team)
  File "/home/ihuguet/Dev/lnst/lnst/Controller/Controller.py", line 161, in run
    recipe.test()
  File "/home/ihuguet/Dev/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 164, in test
    self.do_tests(recipe_config)
  File "/home/ihuguet/Dev/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 285, in do_tests
    self.do_ping_tests(recipe_config)
  File "/home/ihuguet/Dev/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 295, in do_ping_tests
    for ping_configs in self.generate_ping_configurations(recipe_config):
  File "/home/ihuguet/Dev/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 342, in generate_ping_configurations
    raise LnstError("Source/destination ip lists are of different size.")
lnst.Common.LnstError.LnstError: Source/destination ip lists are of different size.
```
Adding some log messages to BaseEnrtRecipe.py, generate_ping_configurations, I see this IPv6 lists:
```
TeamDevice(machine=host1, id=team0, name=t_team0, ifindex=22)
[Ip6Address(fc00:0:0:1::1/64), Ip6Address(fd00::1e1b:dff:fe9d:b048/64)]
Device(machine=host2, id=eth0, name=enp4s0f4d1, ifindex=7)
[Ip6Address(fc00:0:0:1::2/64)]
```

In the slave, I confirm that info:
```
# ip addr show t_team0
22: t_team0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 1c:1b:0d:9d:b0:48 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.1/24 scope global t_team0
       valid_lft forever preferred_lft forever
    inet6 fd00::1e1b:dff:fe9d:b048/64 scope global dynamic mngtmpaddr
       valid_lft 86394sec preferred_lft 14394sec
    inet6 fc00:0:0:1::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::1e1b:dff:fe9d:b048/64 scope link
       valid_lft forever preferred_lft forever
```

It seems that this "mngtmpaddr" is obtained automatically by Neighbor Discovery Protocol (NDP), with Router Solicitation and Router Advertisement messages: https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol, not with DHCP.

First I was confused because this happened  only for bond and team devices, and not for normal NIC ports devices. Finally I found that normal NIC devices has `sysctl net.ipv6.conf.INTERFACE.accept_ra = 0`, but for bond and team devices it's `1`. The reason for this is that NetworkManager was configuring the interfaces at startup, setting `accept_ra=0`, but new devices created with iproute get the values from `net.ipv6.conf.default.*`, where `net.ipv6.conf.default.accept_ra=1`.

Probably "Neighbor Discovery Protocol" could be considered much like DHCP, so supposed not to be used when testing with LNST. However, I think that it would be good to use only the IP addresses list configured by LNST, and no other ones, so tests can be done even if NDP happens.

**Comment by olichtne** [comment]
yup, makes sense from the recipe point of view. I think in general I want lnst to still see everything available/possible wrt. the devices. But the proposal makes sense for the way that we've implemented the `ENRT` recipes...

I've been thinking about adding some sort of a `validate configuration` step that happens after the various configuration steps. This would check that the network is in a state that we expect and it could optionally error/warn if there's something wrong of if there's a *suspected* difference (such as an extra ip address that isn't ours).

After that if the validation passes, the actual test phase shouldn't need to live query the systems and should just rely on the output of the configuration and it's validation.

This may be a medium/larger type of refactoring though... so I'll try to also think of an *in-between* step so that we at least don't crash in situations such as you're reporting.

**Comment by naggety** [comment]
I've been able to successfully complete the test doing a `sysctl net.ipv6.conf.default.accept_ra=0` in the slaves prior to running the tests. I don't know if you consider that a good enough in-between workaround.

**Comment by olichtne** [comment]
yes, i'd say that is a good immediate sort of workaround that our team or myself would use directly in our lab/testing infrastructure, but this would be done as an extra step that's done before running lnst.

For an in-between step in LNST, I'd probably be thinking about just changing the test phase to be implemented in the final step that i've described - rely on the fact that everything is correctly configured, without having the validation step. And rely on the fact that the infrastructure and recipes are setup/implemented in a way that this works 99% of the time.

The remaining 1% of the time would be crashes, that would happen in case the configuration phase happened incorrectly and validation would catch it and fail the recipe. Having a soft crash (deconfiguration would still be called) here instead of a clean fail is probably ok for now as the test wouldn't have been relevant anyway if the configuration wasn't complete.

@naggety Does it makes sense for you to handle the `sysctl net.ipv6.conf.default.accept_ra=0` command outside of lnst for now in your setup?

**Comment by naggety** [comment]
Yes, no problem, is what I've done, in fact.
